stages:
  - deploy
 
deploy_infraestrutura:
  stage: deploy
  tags:
    - meu-runner-local
  script:
    - echo "A iniciar o deploy automatico com segredos do Vault..."
    - cd infra
    # Argumento --vault-password-file para o Ansible saber ler o segredo localmente sem travar a pipeline
    - sudo ansible-playbook -i "localhost," -c local --vault-password-file /home/daniel/.vault_pass.txt deploy_servicos.yml
    - echo "Deploy concluido com sucesso!"