version: '3.8'

services:
  # O nosso Reverse Proxy / Servidor Web
  proxy_web:
    image: nginx:latest
    container_name: nginx_proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./web:/usr/share/nginx/html:ro # Injeta a pasta web para dentro do Nginx (Read-Only como prática de segurança)
    networks:
      - rede_interna

  # Servidor DNS (Pi-Hole)
  servidor_dns:
    image: pihole/pihole:latest
    container_name: dns_pihole
    restart: unless-stopped
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8080:80" # A porta 8080 vai dar acesso ao painel de controlo do DNS
    environment:
      TZ: 'Europe/Lisbon'
      WEBPASSWORD: '123.,' # Esta será a password do painel
    networks:
      - rede_interna

# --- OBSERVABILIDADE ---
  
  # Node Exporter (Sensores de hardware)
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    restart: unless-stopped
    ports:
      - "9100:9100"
    networks:
      - rede_interna

  # Prometheus (Base de dados de métricas)
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      - rede_interna

  # Grafana (Painéis e Gráficos Visuais)
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin # Password inicial do Grafana
    networks:
      - rede_interna




# VPN (WireGuard)
  wireguard:
    image: lscr.io/linuxserver/wireguard:latest
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Lisbon
      - SERVERURL=2.80.141.30 # O IP do servidor Ubuntu
      - SERVERPORT=51821
      - PEERS=2 # Cria 2 perfis (dois QR Codes para o telemóvel e computador portatil neste caso)
      - PEERDNS=192.168.1.252 # IMPORTANTE: Obriga a VPN a usar o Pi-hole
      - INTERNAL_SUBNET=10.13.13.0
      - ALLOWEDIPS=0.0.0.0/0
    volumes:
      - ./wireguard:/config
    ports:
      - "51821:51821/udp"
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
    networks:
      - rede_interna


# Uma rede isolada para os containers comunicarem de forma segura:
networks:
  rede_interna:
    driver: bridge